project:
  type: website
  output-dir: docs
  resources:
    - cmz_cv_i.pdf

website:
  title: "Chris Zarbock"
  favicon: Christopher_Zarbock.jpeg

format:
  html:
    theme:
      light: flatly
      #dark: darkly
    css: styles.css
    toc: false