project:
  type: website
  output-dir: docs
  resources:
    - cmz_cv_final.pdf

website:
  title: "Chris Zarbock"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false