project:
  type: website
  output-dir: docs
  resources:
    - cmz_cv_final.pdf

website:
  title: "Chris Zarbock"
  favicon: day_at_the_zoo.jpeg

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false