project:
  type: website
  output-dir: docs

website:
  title: "Chris Zarbock"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



